# Instalar el paquete foreign si no lo tienes
install.packages("foreign")

# Cargar el paquete
library(foreign)

# Leer el archivo .sav

data2 <- read.spss("/Users/oliverrodas/Downloads/20240522235219ITIf0Taxw7mbshQNenoLw9A9K5cR4pMt.sav", to.data.frame = TRUE)

#cambio para sexo
data2$Sexo <- factor(data2$Sexo, levels = c("Hombre", "Mujer"), labels = c(1, 2))

#cambio para Sector
data2$Sector <- factor(data2$Sector, levels = c("Público", "Privado", "Municipal", "Cooperativa"), labels = c(1, 2, 3, 4))

#cambio para Area
data2$Área <- factor(data2$Área, levels = c("Urbana", "Rural", "Ignorado"), labels = c(1, 2, 9))

#cambio Jornada
data2$Jornada_Est <- factor(data2$Jornada_Est, levels = c("Matutina", "Vespertina", "Noturna", "Doble", "Internmedia", "Sin jornada"), labels = c(1, 2, 3, 4, 5, 9))

#cambio Resultado Final
data2$Resultado_F <- factor(data2$Resultado_F, levels = c("Promovido", "Vigente", "Retirado por traslado", "Retirado definitivo", "No promovido", "Ignorado"), labels = c(1, 2, 3, 4, 5, 9))

#plan de estudio
data2$Plan_Est <- factor(data2$Plan_Est, levels = c("Diario", "Fin de semana", "Virtual a distancia", "Semipresencial", "Mixto"), labels = c(1, 2, 3, 4, 5))

#Nivel
data2$Nivel <- factor(data2$Nivel, levels = c("Preprimaria", "Primaria", "Básicos", "Diversificado", "Primaria de adultos"), labels = c(1, 2, 3, 4, 5))

#Pueblo de pertenencia
data2$Pueblo_Per <- factor(data2$Pueblo_Per, levels = c("Ladino/Mestizo", "Maya", "Garífuna", "Xinka", "Extranjero", "Ignorado"), labels = c(1, 2, 3, 4, 5,9))



#departamentos
data2$Departamento_F <- factor(data2$Departamento_F, levels = c("Guatemala", "El Progreso", "Sacatepéquez", "Chimaltenango", "Escuintla", "Santa Rosa", "Sololá", "Totonicapán", "Quetzaltenango", "Suchitepéquez", "Retalhuleu", "San Marcos", "Huehuetenango", "Quiché", "Baja Verapaz", "Alta Verapaz", "Péten", "Izabal", "Zacapa", "Chiquimula", "Jalapa", "Jutiapa"), labels = 1:22)

#mupiosprueba
data2$Depto_mupio <- factor(data2$Depto_mupio, levels = c("Guatemala"), labels = c("0101"))

data2$Depto_mupio <- factor(data2$Depto_mupio, levels = unique(data2$Depto_mupio), labels = c("0101"))

levels(data2$Depto_mupio)[levels(data2$Depto_mupio) == "Guatemala"] <- "0101"

install.packages("dplyr")
library(dplyr)
data2$Depto_mupio <- recode(data2$Depto_mupio, "Guatemala" = "0101")

data2$Depto_mupio <- recode(data2$Depto_mupio,
                            "Guatemala" = "guuatemala",
                            "Mixco" = "0102",
                            "Villa Nueva" = "0103")

data2$Depto_mupio <- factor(data2$Depto_mupio)

#mupios
data2$Depto_mupio <- factor(data2$Depto_mupio, levels = c("Guatemala",
"Santa Catarina Pinula",
"San José Pinula",
"San José del Golfo",
"Palencia",
"Chinautla",
"San Pedro Ayampuc",
"Mixco",
"San Pedro Sacatepéquez",
"San Juan Sacatepéquez",
"San Raymundo",
"Chuarrancho",
"Fraijanes",
"Amatitlán",
"Villa Nueva",
"Villa Canales",
"Petapa",
"Guastatoya",
"Morazán",
"San Agustín Acasagustlán",
"San Cristóbal Acasaguastlán",
"El Jícaro",
"Sansare",
"Sanarate",
"San Antonio la Paz",
"Antigua Guatemala",
"Jocotenango",
"Pastores",
"Sumpango",
"Santo Domingo Xenacoj",
"Santiago Sacatepéquez",
"San Bartolomé Milpas Altas",
"San Lucas Sacatepéquez",
"Santa Lucía Milpas Altas",
"Magdalena Milpas Altas",
"Santa María de Jesús",
"Ciudad Vieja",
"San Miguel Dueñas",
"San Juan Alotenango",
"San Antonio Aguas Calientes",
"Santa Catarina Barahona",
"Chimaltenango",
"San José Poaquil",
"San Martín Jilotepeque",
"Comalapa",
"Santa Apolonia",
"Tecpán Guatemala",
"Patzún",
"Pochuta",
"Patzicía",
"Santa Cruz Balanyá",
"Acatenango",
"Yepocapa",
"San Andrés Itzapa",
"Parramos",
"Zaragoza",
"El Tejar",
"Escuintla",
"Santa Lucía Cotzumalguapa",
"La Democracia",
"Siquinalá",
"Masagua",
"Tiquisate",
"La Gomera",
"Guanagazapa",
"San José",
"Iztapa",
"Palín",
"San Vicente Pacaya",
"Nueva Concepción",
"Sipacate",
"Cuilapa",
"Barberena",
"Santa Rosa de Lima",
"Casillas",
"San Rafael Las Flores",
"Oratorio",
"San Juan Tecuaco",
"Chiquimulilla",
"Taxisco",
"Santa María Ixhuatán",
"Guazacapán",
"Santa Cruz el Naranjo",
"Pueblo Nuevo Viñas",
"Nueva Santa Rosa",
"Sololá",
"San José Chacayá",
"Santa María Visitación",
"Santa Lucía Utatlán",
"Nahualá",
"Santa Catarina Ixtahuacán",
"Santa Clara la Laguna",
"Concepción",
"San Andrés Semetabaj",
"Panajachel",
"Santa Catarina Palopó",
"San Antonio Palopó",
"San Lucas Tolimán",
"Santa Cruz La Laguna",
"San Pablo La Laguna",
"San Marcos La Laguna",
"San Juan La Laguna",
"San Pedro La Laguna",
"Santiago Atitlán",
"Totonicapán",
"San Cristóbal Totonicapán",
"San Francisco el Alto",
"San Andrés Xecul",
"Momostenango",
"Santa María Chiquimula",
"Santa Lucía la Reforma",
"San Bartolo",
"Quetzaltenango",
"Salcajá",
"Olintepeque",
"San Carlos Sija",
"Sibilia",
"Cabricán",
"Cajolá",
"San Miguel Siguilá",
"Ostuncalco",
"San Mateo",
"Concepción Chiquirichapa",
"San Martín Sacatepéquez",
"Almolonga",
"Cantel",
"Huitán",
"Zuníl",
"Colomba",
"San Francisco la Unión",
"El Palmar",
"Coatepeque",
"Génova",
"Flores Costa Cuca",
"La Esperanza",
"Palestina de los Altos",
"Mazatenango",
"Cuyotenango",
"San Francisco Zapotitlán",
"San Bernardino",
"San José el Idolo",
"Santo Domingo Suchitepéquez",
"San Lorenzo",
"Samayac",
"San Pablo Jocopilas",
"San Antonio Suchitepéquez",
"San Miguel Panán",
"San Gabriel",
"Chicacao",
"Patulul",
"Santa Bárbara",
"San Juan Bautista",
"Santo Tomás la Unión",
"Zunilito",
"Pueblo Nuevo",
"Rio Bravo",
"La Maquina",
"Retalhuleu",
"San Sebastián",
"Santa Cruz Muluá",
"San Martín Zapotitlán",
"San Felipe",
"San Andrés Villa Seca",
"Champerico",
"Nuevo San Carlos",
"El Asintal",
"San Marcos",
"San Pedro Sacatepéquez",
"San Antonio Sacatepéquez",
"Comitancillo",
"San Miguel Ixtahuacán",
"Concepción Tutuapa",
"Tacaná",
"Sibinal",
"Tajumulco",
"Tejutla",
"San Rafael Pie de La Cuesta",
"Nuevo Progreso",
"El Tumbador",
"El Rodeo",
"Malacatán",
"Catarina",
"Ayutla",
"Ocós",
"San Pablo",
"El Quetzal",
"La Reforma",
"Pajapita",
"Ixchiguán",
"San José Ojetenam",
"San Cristóbal Cucho",
"Sipacapa",
"Esquipulas Palo Gordo",
"Río Blanco",
"San Lorenzo",
"La Blanca",
"Huehuetenango",
"Chiantla",
"Malacatancito",
"Cuilco",
"Nentón",
"San Pedro Necta",
"Jacaltenango",
"San Pedro Soloma",
"San Idelfonso Ixtahuacán",
"Santa Bárbara",
"La Libertad",
"La Democracia",
"San Miguel Acatán",
"San Rafael la Independencia",
"Todos Santos Cuchumatán",
"San Juan Atitán",
"Santa Eulalia",
"San Mateo Ixtatán",
"Colotenango",
"San Sebastián Huehuetenango",
"Tectitán",
"Concepción Huista",
"San Juan Ixcoy",
"San Antonio Huista",
"San Sebastián Coatán",
"Barillas",
"Aguacatán",
"San Rafael Petzal",
"San Gaspar Ixchil",
"Santiago Chimaltenanango",
"Santa Ana Huista",
"Unión Cantinil",
"Petatán",
"Santa Cruz del Quiché",
"Chiché",
"Chinique",
"Zacualpa",
"Chajul",
"Chichicastenango",
"Patzité",
"San Antonio Ilotenango",
"San Pedro Jocopilas",
"Cunén",
"San Juan Cotzal",
"Joyabaj",
"Nebaj",
"San Andrés Sajcabajá",
"San Miguel Uspantán",
"Sacapulas",
"San Bartolomé Jocotenango",
"Canillá",
"Chicamán",
"Ixcán",
"Pachalum",
"Salamá",
"San Miguel Chicaj",
"Rabinal",
"Cubulco",
"Granados",
"El Chol",
"San Jerónimo",
"Purulhá",
"Cobán",
"Santa Cruz Verapaz",
"San Cristóbal Verapaz",
"Tactic",
"Tamahú",
"Tucurú",
"Panzós",
"Senahú",
"San Pedro Carchá",
"San Juan Chamelco",
"Lanquín",
"Cahabón",
"Chisec",
"Chahal",
"Fray Bartolomé de las Casas",
"Santa Catarina La Tinta",
"Raxruhá",
"Flores",
"San José",
"San Benito",
"San Andrés",
"La Libertad",
"San Francisco",
"Santa Ana",
"Dolores",
"San Luis",
"Sayaxché",
"Melchor de Mencos",
"Poptún",
"Las Cruces",
"El Chal",
"Puerto Barrios",
"Livingston",
"El Estor",
"Morales",
"Los Amates",
"Zacapa",
"Estanzuela",
"Rio Hondo",
"Gualán",
"Teculután",
"Usumatlán",
"Cabañas",
"San Diego",
"La Unión",
"Huité",
"San Jorge",
"Chiquimula",
"San José La Arada",
"San Juan Ermita",
"Jocotán",
"Camotán",
"Olopa",
"Esquipulas",
"Concepción Las Minas",
"Quezaltepeque",
"San Jacinto",
"Ipala",
"Jalapa",
"San Pedro Pinula",
"San Luis Jilotepeque",
"San Manuel Chaparrón",
"San Carlos Alzatate",
"Monjas",
"Mataquescuintla",
"Jutiapa",
"El Progreso",
"Santa Catarina Mita",
"Agua Blanca",
"Asunción Mita",
"Yupiltepeque",
"Atescatempa",
"Jeréz",
"El Adelanto",
"Zapotitlán",
"Comapa",
"Jalpatagua",
"Conguaco",
"Moyuta",
"Pasaco",
"San José Acatempa",
"Quesada"), labels = c("0101", "0102", "0103", "0104", "0105", "0106", "0107", "0108", "0109", "0110", "0111", "0112",
                      "0113", "0114", "0115", "0116", "0117", "0201", "0202", "0203", "0204", "0205", "0206", "0207", "0208",
                      "0301", "0302", "0303", "0304", "0305", "0306", "0307", "0308", "0309", "0310", "0311", "0312", "0313",
                      "0314", "0315", "0316", "0401", "0402", "0403", "0404", "0405", "0406", "0407", "0408", "0409", "0410",
                      "0411", "0412", "0413", "0414", "0415", "0416", "0501", "0502", "0503", "0504", "0505", "0506", "0507",
                      "0508", "0509", "0510", "0511", "0512", "0513", "0514", "0601", "0602", "0603", "0604", "0605", "0606",
                      "0607", "0608", "0609", "0610", "0611", "0612", "0613", "0614", "0701", "0702", "0703", "0704", "0705",
                      "0706", "0707", "0708", "0709", "0710", "0711", "0712", "0713", "0714", "0715", "0716", "0717", "0718",
                      "0719", "0801", "0802", "0803", "0804", "0805", "0806", "0807", "0808", "0901", "0902", "0903", "0904",
                      "0905", "0906", "0907", "0908", "0909", "0910", "0911", "0912", "0913", "0914", "0915", "0916", "0917",
                      "0918", "0919", "0920", "0921", "0922", "0923", "0924", "1001", "1002", "1003", "1004", "1005", "1006",
                      "1007", "1008", "1009", "1010", "1011", "1012", "1013", "1014", "1015", "1016", "1017", "1018", "1019",
                      "1020", "1021", "1101", "1102", "1103", "1104", "1105", "1106", "1107", "1108", "1109", "1201", "1202",
                      "1203", "1204", "1205", "1206", "1207", "1208", "1209", "1210", "1211", "1212", "1213", "1214", "1215",
                      "1216", "1217", "1218", "1219", "1220", "1221", "1222", "1223", "1224", "1225", "1226", "1227", "1228",
                      "1229", "1230", "1301", "1302", "1303", "1304", "1305", "1306", "1307", "1308", "1309", "1310", "1311",
                      "1312", "1313", "1314", "1315", "1316", "1317", "1318", "1319", "1320", "1321", "1322", "1323", "1324",
                      "1325", "1326", "1327", "1328", "1329", "1330", "1331", "1332", "1333", "1401", "1402", "1403", "1404",
                      "1405", "1406", "1407", "1408", "1409", "1410", "1411", "1412", "1413", "1414", "1415", "1416", "1417",
                      "1418", "1419", "1420", "1421", "1501", "1502", "1503", "1504", "1505", "1506", "1507", "1508", "1601",
                      "1602", "1603", "1604", "1605", "1606", "1607", "1608", "1609", "1610", "1611", "1612", "1613", "1614",
                      "1615", "1616", "1617", "1701", "1702", "1703", "1704", "1705", "1706", "1707", "1708", "1709", "1710",
                      "1711", "1712", "1713", "1714", "1801", "1802", "1803", "1804", "1805", "1901", "1902", "1903", "1904",
                      "1905", "1906", "1907", "1908", "1909", "1910", "1911", "2001", "2002", "2003", "2004", "2005", "2006",
                      "2007", "2008", "2009", "2010", "2011", "2101", "2102", "2103", "2104", "2105", "2106", "2107", "2201",
                      "2202", "2203", "2204", "2205", "2206", "2207", "2208", "2209", "2210", "2211", "2212", "2213", "2214",
                      "2215", "2216", "2217"))

# Verifica los primeros valores
head(data2$Departamento)


unique(data2$Departamento_F)


subset(data2, Departamento_F == NA)


# Ver las primeras filas del dataset
head(data2)

municipios <- c("Guatemala",
"Santa Catarina Pinula",
"San José Pinula",
"San José del Golfo",
"Palencia",
"Chinautla",
"San Pedro Ayampuc",
"Mixco",
"San Pedro Sacatepéquez",
"San Juan Sacatepéquez",
"San Raymundo",
"Chuarrancho",
"Fraijanes",
"Amatitlán",
"Villa Nueva",
"Villa Canales",
"Petapa",
"Guastatoya",
"Morazán",
"San Agustín Acasagustlán",
"San Cristóbal Acasaguastlán",
"El Jícaro",
"Sansare",
"Sanarate",
"San Antonio la Paz",
"Antigua Guatemala",
"Jocotenango",
"Pastores",
"Sumpango",
"Santo Domingo Xenacoj",
"Santiago Sacatepéquez",
"San Bartolomé Milpas Altas",
"San Lucas Sacatepéquez",
"Santa Lucía Milpas Altas",
"Magdalena Milpas Altas",
"Santa María de Jesús",
"Ciudad Vieja",
"San Miguel Dueñas",
"San Juan Alotenango",
"San Antonio Aguas Calientes",
"Santa Catarina Barahona",
"Chimaltenango",
"San José Poaquil",
"San Martín Jilotepeque",
"Comalapa",
"Santa Apolonia",
"Tecpán Guatemala",
"Patzún",
"Pochuta",
"Patzicía",
"Santa Cruz Balanyá",
"Acatenango",
"Yepocapa",
"San Andrés Itzapa",
"Parramos",
"Zaragoza",
"El Tejar",
"Escuintla",
"Santa Lucía Cotzumalguapa",
"La Democracia",
"Siquinalá",
"Masagua",
"Tiquisate",
"La Gomera",
"Guanagazapa",
"San José",
"Iztapa",
"Palín",
"San Vicente Pacaya",
"Nueva Concepción",
"Sipacate",
"Cuilapa",
"Barberena",
"Santa Rosa de Lima",
"Casillas",
"San Rafael Las Flores",
"Oratorio",
"San Juan Tecuaco",
"Chiquimulilla",
"Taxisco",
"Santa María Ixhuatán",
"Guazacapán",
"Santa Cruz el Naranjo",
"Pueblo Nuevo Viñas",
"Nueva Santa Rosa",
"Sololá",
"San José Chacayá",
"Santa María Visitación",
"Santa Lucía Utatlán",
"Nahualá",
"Santa Catarina Ixtahuacán",
"Santa Clara la Laguna",
"Concepción",
"San Andrés Semetabaj",
"Panajachel",
"Santa Catarina Palopó",
"San Antonio Palopó",
"San Lucas Tolimán",
"Santa Cruz La Laguna",
"San Pablo La Laguna",
"San Marcos La Laguna",
"San Juan La Laguna",
"San Pedro La Laguna",
"Santiago Atitlán",
"Totonicapán",
"San Cristóbal Totonicapán",
"San Francisco el Alto",
"San Andrés Xecul",
"Momostenango",
"Santa María Chiquimula",
"Santa Lucía la Reforma",
"San Bartolo",
"Quetzaltenango",
"Salcajá",
"Olintepeque",
"San Carlos Sija",
"Sibilia",
"Cabricán",
"Cajolá",
"San Miguel Siguilá",
"Ostuncalco",
"San Mateo",
"Concepción Chiquirichapa",
"San Martín Sacatepéquez",
"Almolonga",
"Cantel",
"Huitán",
"Zuníl",
"Colomba",
"San Francisco la Unión",
"El Palmar",
"Coatepeque",
"Génova",
"Flores Costa Cuca",
"La Esperanza",
"Palestina de los Altos",
"Mazatenango",
"Cuyotenango",
"San Francisco Zapotitlán",
"San Bernardino",
"San José el Idolo",
"Santo Domingo Suchitepéquez",
"San Lorenzo",
"Samayac",
"San Pablo Jocopilas",
"San Antonio Suchitepéquez",
"San Miguel Panán",
"San Gabriel",
"Chicacao",
"Patulul",
"Santa Bárbara",
"San Juan Bautista",
"Santo Tomás la Unión",
"Zunilito",
"Pueblo Nuevo",
"Rio Bravo",
"La Maquina",
"Retalhuleu",
"San Sebastián",
"Santa Cruz Muluá",
"San Martín Zapotitlán",
"San Felipe",
"San Andrés Villa Seca",
"Champerico",
"Nuevo San Carlos",
"El Asintal",
"San Marcos",
"San Pedro Sacatepéquez",
"San Antonio Sacatepéquez",
"Comitancillo",
"San Miguel Ixtahuacán",
"Concepción Tutuapa",
"Tacaná",
"Sibinal",
"Tajumulco",
"Tejutla",
"San Rafael Pie de La Cuesta",
"Nuevo Progreso",
"El Tumbador",
"El Rodeo",
"Malacatán",
"Catarina",
"Ayutla",
"Ocós",
"San Pablo",
"El Quetzal",
"La Reforma",
"Pajapita",
"Ixchiguán",
"San José Ojetenam",
"San Cristóbal Cucho",
"Sipacapa",
"Esquipulas Palo Gordo",
"Río Blanco",
"San Lorenzo",
"La Blanca",
"Huehuetenango",
"Chiantla",
"Malacatancito",
"Cuilco",
"Nentón",
"San Pedro Necta",
"Jacaltenango",
"San Pedro Soloma",
"San Idelfonso Ixtahuacán",
"Santa Bárbara",
"La Libertad",
"La Democracia",
"San Miguel Acatán",
"San Rafael la Independencia",
"Todos Santos Cuchumatán",
"San Juan Atitán",
"Santa Eulalia",
"San Mateo Ixtatán",
"Colotenango",
"San Sebastián Huehuetenango",
"Tectitán",
"Concepción Huista",
"San Juan Ixcoy",
"San Antonio Huista",
"San Sebastián Coatán",
"Barillas",
"Aguacatán",
"San Rafael Petzal",
"San Gaspar Ixchil",
"Santiago Chimaltenanango",
"Santa Ana Huista",
"Unión Cantinil",
"Petatán",
"Santa Cruz del Quiché",
"Chiché",
"Chinique",
"Zacualpa",
"Chajul",
"Chichicastenango",
"Patzité",
"San Antonio Ilotenango",
"San Pedro Jocopilas",
"Cunén",
"San Juan Cotzal",
"Joyabaj",
"Nebaj",
"San Andrés Sajcabajá",
"San Miguel Uspantán",
"Sacapulas",
"San Bartolomé Jocotenango",
"Canillá",
"Chicamán",
"Ixcán",
"Pachalum",
"Salamá",
"San Miguel Chicaj",
"Rabinal",
"Cubulco",
"Granados",
"El Chol",
"San Jerónimo",
"Purulhá",
"Cobán",
"Santa Cruz Verapaz",
"San Cristóbal Verapaz",
"Tactic",
"Tamahú",
"Tucurú",
"Panzós",
"Senahú",
"San Pedro Carchá",
"San Juan Chamelco",
"Lanquín",
"Cahabón",
"Chisec",
"Chahal",
"Fray Bartolomé de las Casas",
"Santa Catarina La Tinta",
"Raxruhá",
"Flores",
"San José",
"San Benito",
"San Andrés",
"La Libertad",
"San Francisco",
"Santa Ana",
"Dolores",
"San Luis",
"Sayaxché",
"Melchor de Mencos",
"Poptún",
"Las Cruces",
"El Chal",
"Puerto Barrios",
"Livingston",
"El Estor",
"Morales",
"Los Amates",
"Zacapa",
"Estanzuela",
"Rio Hondo",
"Gualán",
"Teculután",
"Usumatlán",
"Cabañas",
"San Diego",
"La Unión",
"Huité",
"San Jorge",
"Chiquimula",
"San José La Arada",
"San Juan Ermita",
"Jocotán",
"Camotán",
"Olopa",
"Esquipulas",
"Concepción Las Minas",
"Quezaltepeque",
"San Jacinto",
"Ipala",
"Jalapa",
"San Pedro Pinula",
"San Luis Jilotepeque",
"San Manuel Chaparrón",
"San Carlos Alzatate",
"Monjas",
"Mataquescuintla",
"Jutiapa",
"El Progreso",
"Santa Catarina Mita",
"Agua Blanca",
"Asunción Mita",
"Yupiltepeque",
"Atescatempa",
"Jeréz",
"El Adelanto",
"Zapotitlán",
"Comapa",
"Jalpatagua",
"Conguaco",
"Moyuta",
"Pasaco",
"San José Acatempa",
"Quesada")

# Filtrar registros excluidos
registros_excluidos <- data2 %>% filter(Depto_mupio %in%)





################ reglas #######################

install.packages("arules")

library("arules")


#apriori

reglas <- apriori(data2, parameter = list(support=0.2, confidence=0.5 ))

data2 <- subset(data2, select = -Año)

inspect(reglas[100:200])

reglasframe <- as(reglas, "data.frame")


################# Reglas de asociación FP-Growth ############

dataFP2 <- data2[, c(2,3,4,5,6,7,8,9,10,11,12,13,14)]



reglasFP <- apriori(data2, parameter = list(supp = 0.2, conf = 0.6, target = "rules"))
summary(rules)

reglasframeFP <- as(reglasFP, "data.frame")

dataFP2 <- data.frame(dataFP2)

dataFP2D <- subset(dataFP2, Departamento_F == 22)
